package stream2;

import java.util.ArrayList;
import java.util.List;

public class Data {
    static List<Person> people = new ArrayList<>() {
        {
            add(new Person("Bree Mayer", "Peru", 25, 14.68));
            add(new Person("Guinevere Mckinney", "China", 49, 69.23));
            add(new Person("Kelly Erickson", "Nigeria", 25, 72.92));
            add(new Person("Aristotle Boyd", "Spain", 29, 25.85));
            add(new Person("Leah Stone", "Ukraine", 36, 9.84));
            add(new Person("Evangeline Riddle", "France", 47, 32.34));
            add(new Person("Adrienne Contreras", "Sweden", 44, 38.61));
            add(new Person("Jarrod Rivera", "United Kingdom", 35, 31.81));
            add(new Person("Quinn Oneal", "United States", 27, 81.60));
            add(new Person("Brody Glenn", "Ukraine", 34, 19.82));
            add(new Person("Tyler Jones", "Germany", 45, 83.96));
            add(new Person("Cantha Kidd", "Turkey", 36, 28.97));
            add(new Person("Hope Boyle", "Vietnam", 35, 83.97));
            add(new Person("David Willis", "Belgium", 21, 2.58));
            add(new Person("Claudia Humphrey", "Chile", 25, 93.26));
            add(new Person("Reinaldo Silva", "Brazil", 37, 30.81));
            add(new Person("Philip Fry", "United States", 49, 20.45));
            add(new Person("Denton Duran", "Russian Federation", 20, 16.79));
            add(new Person("Linda Stark", "Spain", 21, 66.81));
            add(new Person("MacKensie Welch", "Austria", 28, 34.43));
            add(new Person("Chantale Whitney", "Vietnam", 36, 33.88));
            add(new Person("Joshua Castro", "China", 42, 59.91));
            add(new Person("Guy Conley", "Austria", 38, 93.71));
            add(new Person("Thomas Griffin", "Russian Federation", 43, 55.24));
            add(new Person("Adena Alston", "Canada", 42, 58.89));
            add(new Person("Delilah Mullins", "Philippines", 32, 54.92));
            add(new Person("Jayme Anderson", "Turkey", 49, 87.78));
            add(new Person("Ginger Delacruz", "Pakistan", 25, 56.26));
            add(new Person("Grady Carney", "Canada", 19, 56.57));
            add(new Person("Rose Farley", "India", 32, 17.97));
            add(new Person("Macy Fitzpatrick", "United States", 23, 79.24));
            add(new Person("Aline Daniel", "United States", 33, 34.77));
            add(new Person("Jescie Rogers", "Nigeria", 29, 61.89));
            add(new Person("Ulla Foster", "China", 23, 20.58));
            add(new Person("Gwendolyn Alvarez", "Ireland", 39, 4.07));
            add(new Person("Blythe Phillips", "United Kingdom", 42, 63.25));
            add(new Person("Lareina Cummings", "Chile", 42, 84.63));
            add(new Person("Nyssa Mayer", "Belgium", 26, 41.38));
            add(new Person("Barrett Ramsey", "Singapore", 39, 62.27));
            add(new Person("Hall English", "Ukraine", 19, 60.44));
            add(new Person("Theodore Harding", "Ireland", 23, 2.40));
            add(new Person("Bree Owens", "Pakistan", 23, 60.85));
            add(new Person("Constance Dean", "Russian Federation", 24, 67.79));
            add(new Person("Oliver Kramer", "Sweden", 30, 77.74));
            add(new Person("Denise Potts", "South Korea", 38, 15.48));
            add(new Person("Malcolm Patrick", "South Africa", 29, 48.52));
            add(new Person("Desirae Ayala", "India", 24, 77.18));
            add(new Person("Axel Stephens", "Philippines", 28, 95.50));
            add(new Person("Berk Woodard", "China", 23, 69.03));
            add(new Person("Fritz Tanner", "Indonesia", 33, 66.13));
            add(new Person("Iliana Roy", "Canada", 24, 64.60));
            add(new Person("Maris Logan", "United Kingdom", 25, 63.93));
            add(new Person("Ariana Roach", "South Africa", 49, 21.99));
            add(new Person("Wynter Garrison", "Mexico", 33, 15.35));
            add(new Person("Diana Daniels", "Norway", 42, 27.10));
            add(new Person("Ronan Hebert", "South Africa", 41, 48.51));
            add(new Person("Sage Hanson", "Norway", 41, 80.94));
            add(new Person("Kenyon Mathis", "United States", 24, 86.70));
            add(new Person("Nichole Fitzgerald", "Indonesia", 34, 96.66));
            add(new Person("Theodore Turner", "Ireland", 40, 95.10));
            add(new Person("Alice Rich", "Ireland", 45, 67.97));
            add(new Person("Clarke Stanley", "Norway", 20, 43.16));
            add(new Person("Jenette Schneider", "Mexico", 37, 30.68));
            add(new Person("Ori Ramirez", "Peru", 50, 0.94));
            add(new Person("Dario Santos", "Brazil", 36, 91.19));
            add(new Person("Austin Willis", "Vietnam", 36, 81.47));
            add(new Person("Kaye Blevins", "South Korea", 33, 83.50));
            add(new Person("Genevieve Callahan", "Austria", 44, 21.03));
            add(new Person("Eve Jimenez", "Russian Federation", 34, 38.79));
            add(new Person("Donna Freeman", "Singapore", 24, 24.99));
            add(new Person("Lance Keith", "Costa Rica", 37, 89.44));
            add(new Person("Axel Marsh", "Australia", 20, 74.65));
            add(new Person("Maggie Holmes", "Poland", 47, 75.92));
            add(new Person("Chanda Hooper", "Canada", 47, 85.25));
            add(new Person("Knox Santos", "Nigeria", 40, 67.26));
            add(new Person("Keith Barr", "Chile", 44, 74.55));
            add(new Person("Fabiano Sintra", "Brazil", 32, 25.33));
            add(new Person("Ernesto Sampaio", "Brazil", 28, 19.65));
            add(new Person("Winifred Charles", "Peru", 38, 41.27));
            add(new Person("Hop Jennings", "Poland", 18, 40.49));
            add(new Person("Germaine Solomon", "Costa Rica", 20, 95.23));
            add(new Person("Haley Weiss", "Norway", 43, 75.73));
            add(new Person("Erin Roberts", "Belgium", 48, 28.81));
            add(new Person("Cooper Patrick", "Mexico", 41, 25.52));
            add(new Person("Kermit Phillips", "India", 42, 63.41));
            add(new Person("Libby Hawkins", "New Zealand", 24, 5.51));
            add(new Person("Jameson Gilliam", "New Zealand", 21, 70.27));
            add(new Person("Hector Alvarado", "Austria", 50, 31.48));
            add(new Person("Marcos Cunha", "Brazil", 34, 97.36));
            add(new Person("Petra Austin", "Australia", 26, 36.99));
            add(new Person("Beau Mayer", "Nigeria", 31, 10.87));
            add(new Person("Keane Cooke", "France", 48, 91.53));
            add(new Person("Fleur Mclaughlin", "Spain", 22, 74.89));
            add(new Person("Vivian Emerson", "Belgium", 41, 39.86));
            add(new Person("Elton Ayers", "New Zealand", 40, 62.23));
            add(new Person("Armando Pires", "Brazil", 46, 19.31));
            add(new Person("Colby Decker", "Belgium", 35, 54.62));
            add(new Person("Shellie Howell", "Russian Federation", 29, 86.63));
            add(new Person("Yoshi Watkins", "China", 48, 66.90));
            add(new Person("Ramona Cleveland", "Ireland", 42, 97.19));
        }
    };

    public static List<Person> getPeople() {
        return people;
    }
}
